### ISSUE TITLE
Doesn't ring

### ISSUE THREAD

**Issue by ayZagen** [creativitRy/WoxTimer#1]
It says it will ring but it doesn't

**Comment by creativitRy** [comment]
It produces three windows bell sounds for me. Do you any visual feedback for when the alarm stops?

**Comment by ayZagen** [comment]
@creativitRy Yes I can see the notification but no sound.

**EDIT**: If you are using windows bell sound they are disabled. I hate windows sounds. If this is the case can you make an option to select sound file ?

**Comment by creativitRy** [comment]
Ah, thanks for letting me know. I'll try adding customizable sounds when I get time.

**Comment by LesterCovax** [comment]
@ayZagen I too had system sounds turned off, so I ended up creating a new profile off of the blank one that only enables the `Default Beep` sound, and also changed it to a less annoying sound (Windows Baloon.wav, or choose your own).

@creativitRy The `soundPlayer` class should do the trick
https://docs.microsoft.com/en-us/dotnet/api/system.media.soundplayer?view=netframework-4.8

**Comment by ayZagen** [comment]
@LesterCovax That could be done, but I am against the existence of `Default Beep` sound :)

**Comment by LesterCovax** [comment]
@ayZagen I'm with you on that one; just providing a less annoying alternative until/if the plugin is updated.  Not sure if it would be worth my time to fork it just to implement the `SoundPlayer` solution in lieu of the current `SystemSound` one.
### ¯\\(°_o)/¯

**Comment by creativitRy** [comment]
Hello, thank you so much for waiting! I finally got around implementing the custom sound feature!
To update, please run `wpm install Timer`. You can set the wav file to play under Wox settings > Plugin > Timer
